import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { headers } from 'next/headers'
import { type ReactNode } from 'react'
import { cookieToInitialState } from 'wagmi'

import { getConfig } from '@/lib/wagmi'
import { Web3Provider } from "@/components/web3-provider";
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Wagmi',
    description: 'Generated by create-wagmi',
}

export default async function RootLayout(props: { children: ReactNode }) {
    const initialState = cookieToInitialState(
        getConfig(),
        (await headers()).get('cookie'),
    )
    return (
        <html lang="en" suppressHydrationWarning>
        <body className={inter.className}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
            <Web3Provider initialState={initialState}>{props.children}</Web3Provider>
        </ThemeProvider>
        </body>
        </html>
    )
}
