"$schema" = "node_modules/wrangler/config-schema.json"
name = "blanc"
main = ".output/server/index.mjs"
compatibility_date = "2025-08-20"
compatibility_flags = [ "nodejs_compat" ]

[assets]
directory = ".output/public"

[observability]
enabled = true

[[kv_namespaces]]
binding = "CACHE"
id = "12528781661d4d939f21558e13721f0d"